In [19]:
import face_recognition
import os
import pickle
import pdb
from tqdm import tqdm
import numpy as np

from flask import Flask, render_template, Response, redirect, url_for
import cv2
import face_recognition
import pickle

In [2]:
reference_images_dir = '../data/imgs/his/'
encodings = []

In [6]:
for filename in tqdm(os.listdir(reference_images_dir)):
    try:
        if filename.endswith('.jpg') or filename.endswith('.png'):
            img_path = os.path.join(reference_images_dir, filename)
            image = face_recognition.load_image_file(img_path)
            encoding = face_recognition.face_encodings(image)[0]
            encodings.append(encoding)

    except Exception as e:
        print(e)
        print("Error encountered in filename: ", img_path)

 37%|███▋      | 11/30 [01:06<01:48,  5.71s/it]

list index out of range
Error encountered in filename:  ../data/imgs/his/IMG-20241101-WA0330.jpg


 40%|████      | 12/30 [01:11<01:37,  5.43s/it]

list index out of range
Error encountered in filename:  ../data/imgs/his/IMG-20241101-WA0331.jpg


 47%|████▋     | 14/30 [01:24<01:36,  6.06s/it]

list index out of range
Error encountered in filename:  ../data/imgs/his/IMG-20241127-WA0076.jpg


 50%|█████     | 15/30 [01:31<01:37,  6.51s/it]

list index out of range
Error encountered in filename:  ../data/imgs/his/IMG-20241127-WA0078.jpg


100%|██████████| 30/30 [03:52<00:00,  7.74s/it]


In [ ]:
with open('../ccino_face.pkl', 'wb') as f:
    pickle.dump(encodings, f)

In [4]:
with open('../ccino_face.pkl', 'rb') as f:
    known_face_encodings = pickle.load(f)

In [45]:
def gen():
    cap = cv2.VideoCapture(0)
    print("trying camera")
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        # Resize frame for faster processing
        small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)
        # rgb_small_frame = small_frame[:, :, ::-1]
        rgb_small_frame = np.ascontiguousarray(small_frame[:, :, ::-1])

        # Recognize face
        face_locations = face_recognition.face_locations(rgb_small_frame)
        # print(type(rgb_small_frame))
        # print(rgb_small_frame)

        # print(type(face_locations))
        # print(face_locations)

        face_encodings = face_recognition.face_encodings(rgb_small_frame, face_locations)
        match_found = False
        for face_encoding in face_encodings:
            matches = face_recognition.compare_faces(known_face_encodings, face_encoding)
            if True in matches:
                match_found = True
                break
        
        if match_found:
            cap.release()
            print("A match was found! You can go ahead!")

        ret, jpeg = cv2.imencode('.jpg', frame)
        cv2.imshow('Facial Recognition', frame)

        if cv2.waitKey(1) & 0xFF == ord('q'):
            break

    cv2.destroyAllWindows()
        # break

In [46]:
gen()

trying camera


In [14]:
gen()

trying camera
<class 'numpy.ndarray'>
[[[255 255 255]
  [255 255 253]
  [255 255 252]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 254]
  [255 255 254]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[233 206 189]
  [219 212 211]
  [225 205 211]
  ...
  [115 114 104]
  [112 112 101]
  [110 110  98]]

 [[236 201 200]
  [223 211 214]
  [222 209 211]
  ...
  [117 112 101]
  [114 109  98]
  [112 108  98]]

 [[226 208 194]
  [226 209 209]
  [230 205 206]
  ...
  [112 112 106]
  [110 110 105]
  [105 106  96]]]
<class 'list'>
[]
<class 'numpy.ndarray'>
[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[253 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 2

TypeError: compute_face_descriptor(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], face: _dlib_pybind11.full_object_detection, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vector
    2. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], num_jitters: int = 0) -> _dlib_pybind11.vector
    3. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], faces: _dlib_pybind11.full_object_detections, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectors
    4. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: list[numpy.ndarray[(rows,cols,3),numpy.uint8]], batch_faces: list[_dlib_pybind11.full_object_detections], num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectorss
    5. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: list[numpy.ndarray[(rows,cols,3),numpy.uint8]], num_jitters: int = 0) -> _dlib_pybind11.vectors

Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x0000016CB6CB4EF0>, array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 253],
        [255, 255, 253],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 252],
        [255, 255, 253],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[177, 155, 102],
        [191, 171,  98],
        [222, 203, 160],
        ...,
        [128, 131, 120],
        [126, 126, 117],
        [124, 123, 112]],

       [[162, 146,  84],
        [186, 162,  92],
        [223, 205, 173],
        ...,
        [128, 129, 119],
        [126, 126, 114],
        [121, 119, 107]],

       [[156, 140,  88],
        [180, 142,  99],
        [229, 204, 171],
        ...,
        [125, 124, 119],
        [121, 121, 113],
        [118, 119, 110]]], shape=(120, 160, 3), dtype=uint8), <_dlib_pybind11.full_object_detection object at 0x0000016CDADA5FB0>, 1